const books = [
  {
    "title": "Homo Zapiens",
    "publishedDate": 2002,
    "pageCount": 324,
    "category": "Fiction",
    "averageRating": 3.5,
    "imageLink": "http://books.google.com/books/content?id=Pmwhq_ZJPNkC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 9.99,
    "popular": false,
    "cart": false,
    "id": 0
  },
  {
    "title": "The Sacred Book of the Werewolf",
    "publishedDate": 2008,
    "pageCount": 352,
    "category": "Fiction",
    "averageRating": 3.5,
    "imageLink": "http://books.google.com/books/content?id=FVlXRgIasmEC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 12.99,
    "popular": false,
    "cart": false,
    "id": 1
  },
  {
    "title": "Roadside Picnic",
    "publishedDate": 2012,
    "pageCount": 224,
    "category": "Fiction",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=AC1ACia5WjwC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 12.99,
    "popular": true,
    "cart": false,
    "id": 2
  },
  {
    "title": "Ham On Rye",
    "publishedDate": 2009,
    "pageCount": 288,
    "category": "Fiction",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=Rv4qbAACPzYC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 6.99,
    "popular": false,
    "cart": false,
    "id": 3
  },
  {
    "title": "One Flew Over the Cuckoo's Nest",
    "publishedDate": 2012,
    "pageCount": 320,
    "category": "Fiction",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=wCP2qgXwXdUC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 12.99,
    "popular": false,
    "cart": false,
    "id": 4
  },
  {
    "title": "JavaScript: The Good Parts",
    "publishedDate": 2008,
    "pageCount": 172,
    "category": "Computers",
    "averageRating": 4.5,
    "imageLink": "http://books.google.com/books/content?id=PXa2bby0oQ0C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 23.99,
    "popular": false,
    "cart": false,
    "id": 5
  },
  {
    "title": "Structure and Interpretation of Computer Programs",
    "publishedDate": 2022,
    "pageCount": 640,
    "category": "Computers",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=WSUuEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 38.99,
    "popular": true,
    "cart": false,
    "id": 6
  },
  {
    "title": "The Nature of Space and Time",
    "publishedDate": 2010,
    "pageCount": 160,
    "category": "Science",
    "averageRating": 4.5,
    "imageLink": "http://books.google.com/books/content?id=6a-agBFWuyQC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 14.95,
    "popular": false,
    "cart": false,
    "id": 7
  },
  {
    "title": "My Brief History",
    "publishedDate": 2013,
    "pageCount": 144,
    "category": "Science",
    "averageRating": 3,
    "imageLink": "http://books.google.com/books/content?id=zU0TAAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 13.99,
    "popular": false,
    "cart": false,
    "id": 8
  },
  {
    "title": "Black Holes",
    "publishedDate": 2016,
    "pageCount": 71,
    "category": "Science",
    "averageRating": 3,
    "imageLink": "http://books.google.com/books/content?id=sj3FDAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 2.99,
    "popular": false,
    "cart": false,
    "id": 9
  },
  {
    "title": "Brief Answers to the Big Questions",
    "publishedDate": 2018,
    "pageCount": 256,
    "category": "Science",
    "averageRating": 4.5,
    "imageLink": "http://books.google.com/books/content?id=tFhbDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 9.99,
    "popular": false,
    "cart": false,
    "id": 10
  },
  {
    "title": "God and Stephen Hawking",
    "publishedDate": 2011,
    "pageCount": 96,
    "category": "Religion",
    "averageRating": 4.5,
    "imageLink": "http://books.google.com/books/content?id=zyOa6gJNJoYC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 5.95,
    "popular": false,
    "cart": false,
    "id": 11
  },
  {
    "title": "Bad Religion",
    "publishedDate": 2012,
    "pageCount": 352,
    "category": "Religion",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=AMINYColockC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 13.99,
    "popular": false,
    "cart": false,
    "id": 12
  },
  {
    "title": "The Meaning and End of Religion",
    "publishedDate": 1991,
    "pageCount": 340,
    "category": "Religion",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=PNl1QexhUlIC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 29,
    "popular": false,
    "cart": false,
    "id": 13
  },
  {
    "title": "Comparative Religion",
    "publishedDate": 1987,
    "pageCount": 225,
    "category": "Religion",
    "averageRating": 1,
    "imageLink": "http://books.google.com/books/content?id=Jb0rCQD9NcoC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 11.2,
    "popular": false,
    "cart": false,
    "id": 14
  },
  {
    "title": "Marx on Religion",
    "publishedDate": 2002,
    "pageCount": 254,
    "category": "Philosophy",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=QxWptakXMu0C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 23.95,
    "popular": true,
    "cart": false,
    "id": 15
  },
  {
    "title": "Introduction to Religious Philosophy",
    "publishedDate": 1991,
    "pageCount": 410,
    "category": "Fiction",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=UKfyL88IQjsC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 11.2,
    "popular": false,
    "cart": false,
    "id": 16
  },
  {
    "title": "A Documentary History of Religion in America to 1877",
    "publishedDate": 2003,
    "pageCount": 607,
    "category": "Religion",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=k1wxhByockcC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 45,
    "popular": true,
    "cart": false,
    "id": 17
  },
  {
    "title": "Plato's Republic, Books 1-10",
    "publishedDate": 2001,
    "pageCount": 408,
    "category": "Philosophy",
    "averageRating": 3,
    "imageLink": "http://books.google.com/books/content?id=Ccr8skxseKQC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 9.25,
    "popular": false,
    "cart": false,
    "id": 18
  },
  {
    "title": "A Discourse on the Method",
    "publishedDate": 2006,
    "pageCount": 160,
    "category": "Philosophy",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=9nceZBjaiKoC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 5.99,
    "popular": false,
    "cart": false,
    "id": 19
  },
  {
    "title": "History of Western Philosophy",
    "publishedDate": 2008,
    "pageCount": 928,
    "category": "Philosophy",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=iQZ6Xk9VdtAC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 21.99,
    "popular": false,
    "cart": false,
    "id": 20
  },
  {
    "title": "The Will to Power",
    "publishedDate": 2017,
    "pageCount": 320,
    "category": "Fiction",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=mcO_DAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 14.09,
    "popular": true,
    "cart": false,
    "id": 21
  },
  {
    "title": "The World as Will and Representation",
    "publishedDate": 2016,
    "pageCount": 685,
    "category": "Philosophy",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=37O2DAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 1.99,
    "popular": true,
    "cart": false,
    "id": 22
  },
  {
    "title": "The Genesis of Heidegger's Being and Time",
    "publishedDate": 1995,
    "pageCount": 608,
    "category": "Philosophy",
    "averageRating": 3,
    "imageLink": "http://books.google.com/books/content?id=5HzJuF-69xQC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 39.95,
    "popular": false,
    "cart": false,
    "id": 23
  },
  {
    "title": "Handbook on the Economics of Sport",
    "publishedDate": 2006,
    "pageCount": 830,
    "category": "Sports & Recreation",
    "averageRating": 3.5,
    "imageLink": "http://books.google.com/books/content?id=PGRkblShhU8C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 77.6,
    "popular": false,
    "cart": false,
    "id": 24
  },
  {
    "title": "The Anthropology of Sport",
    "publishedDate": 1995,
    "pageCount": 306,
    "category": "Sports & Recreation",
    "averageRating": 3,
    "imageLink": "http://books.google.com/books/content?id=reno4DRX1pAC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 126.95,
    "popular": false,
    "cart": false,
    "id": 25
  },
  {
    "title": "Handbook of Sport Psychology",
    "publishedDate": 2007,
    "pageCount": 1000,
    "category": "Psychology",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=h2m7I96ZStgC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 160,
    "popular": true,
    "cart": false,
    "id": 26
  },
  {
    "title": "The King of Sports",
    "publishedDate": 2013,
    "pageCount": 368,
    "category": "Sports & Recreation",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=PiMlRYQ1vfAC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 7.99,
    "popular": true,
    "cart": false,
    "id": 27
  },
  {
    "title": "Newton's Football",
    "publishedDate": 2013,
    "pageCount": 272,
    "category": "Sports & Recreation",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=kJep4m0DozIC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 9.99,
    "popular": false,
    "cart": false,
    "id": 28
  },
  {
    "title": "Coaching Football For Dummies",
    "publishedDate": 2011,
    "pageCount": 384,
    "category": "Sports & Recreation",
    "averageRating": 1,
    "imageLink": "http://books.google.com/books/content?id=OIzwNBU6qlAC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 15,
    "popular": false,
    "cart": false,
    "id": 29
  },
  {
    "title": "Champagne Football",
    "publishedDate": 2020,
    "pageCount": 336,
    "category": "Sports & Recreation",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=YrzJDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 14.09,
    "popular": false,
    "cart": false,
    "id": 30
  },
  {
    "title": "Beauty and the Beast",
    "publishedDate": 2017,
    "pageCount": 240,
    "category": "Fiction",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=J195DAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 13.99,
    "popular": false,
    "cart": false,
    "id": 31
  },
  {
    "title": "The Grimm Reader: The Classic Tales of the Brothers Grimm",
    "publishedDate": 2010,
    "pageCount": 368,
    "category": "Fiction",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=XBc_M8ewXPMC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 16.95,
    "popular": true,
    "cart": false,
    "id": 32
  },
  {
    "title": "Flash Fiction International: Very Short Stories from Around the World",
    "publishedDate": 2015,
    "pageCount": 288,
    "category": "Fiction",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=ScWlBwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 16.95,
    "popular": true,
    "cart": false,
    "id": 33
  },
  {
    "title": "Border Districts",
    "publishedDate": 2018,
    "pageCount": 144,
    "category": "Fiction",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=B-80DwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 11.99,
    "popular": false,
    "cart": false,
    "id": 34
  },
  {
    "title": "The Fall of the House of Usher",
    "publishedDate": 2021,
    "pageCount": 88,
    "category": "Fiction",
    "averageRating": 3,
    "imageLink": "http://books.google.com/books/content?id=iOQ9EAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 4.99,
    "popular": false,
    "cart": false,
    "id": 35
  },
  {
    "title": "Fan Fiction",
    "publishedDate": 2021,
    "pageCount": 272,
    "category": "Fiction",
    "averageRating": 3.5,
    "imageLink": "http://books.google.com/books/content?id=nB8QEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 14.99,
    "popular": false,
    "cart": false,
    "id": 36
  },
  {
    "title": "Futurescapes",
    "publishedDate": 2009,
    "pageCount": 366,
    "category": "Fiction",
    "averageRating": 3.5,
    "imageLink": "http://books.google.com/books/content?id=nB8QEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 14.99,
    "popular": false,
    "cart": false,
    "id": 37
  },
  {
    "title": "The Psychology Book",
    "publishedDate": 2015,
    "pageCount": 352,
    "category": "Psychology",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=qZKbBgAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 9.99,
    "popular": true,
    "cart": false,
    "id": 38
  },
  {
    "title": "Handbook of Positive Psychology",
    "publishedDate": 2001,
    "pageCount": 848,
    "category": "Psychology",
    "averageRating": 4.5,
    "imageLink": "http://books.google.com/books/content?id=2Cr5rP8jOnsC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 56.99,
    "popular": false,
    "cart": false,
    "id": 39
  },
  {
    "title": "The Comprehensive History of Psychology",
    "publishedDate": 1991,
    "pageCount": 519,
    "category": "Psychology",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=dXZnwvs6gYIC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 128,
    "popular": false,
    "cart": false,
    "id": 40
  },
  {
    "title": "Psychology and Religion",
    "publishedDate": 1960,
    "pageCount": 138,
    "category": "Psychology",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=q8xk2-0VT8IC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 17.5,
    "popular": false,
    "cart": false,
    "id": 41
  },
  {
    "title": "Critical Psychology",
    "publishedDate": 2009,
    "pageCount": 496,
    "category": "Psychology",
    "averageRating": 3,
    "imageLink": "http://books.google.com/books/content?id=zbTYJ2Mz9jQC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 73,
    "popular": false,
    "cart": false,
    "id": 42
  },
  {
    "title": "Stickhandling through the Margins",
    "publishedDate": 2012,
    "pageCount": 176,
    "category": "Sports & Recreation",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=WYxpXWqiNlUC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 32.95,
    "popular": true,
    "cart": false,
    "id": 43
  },
  {
    "title": "Gabby",
    "publishedDate": 2011,
    "pageCount": 228,
    "category": "Sports & Recreation",
    "averageRating": 3,
    "imageLink": "http://books.google.com/books/content?id=YuWfl_s2ci0C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 19.95,
    "popular": false,
    "cart": false,
    "id": 44
  },
  {
    "title": "Grant Fuhr",
    "publishedDate": 2014,
    "pageCount": 320,
    "category": "Sports & Recreation",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=wm9zAwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 14.99,
    "popular": false,
    "cart": false,
    "id": 45
  },
  {
    "title": "Hockey Fight in Canada",
    "publishedDate": 2018,
    "pageCount": 211,
    "category": "Sports & Recreation",
    "averageRating": 4,
    "imageLink": "http://books.google.com/books/content?id=zzhsDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 15.99,
    "popular": false,
    "cart": false,
    "id": 46
  },
  {
    "title": "Understanding Computers and Cognition",
    "publishedDate": 1986,
    "pageCount": 207,
    "category": "Computers",
    "averageRating": 3.5,
    "imageLink": "http://books.google.com/books/content?id=2sRC8vcDYNEC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 20,
    "popular": false,
    "cart": false,
    "id": 47
  },
  {
    "title": "But how Do it Know?",
    "publishedDate": 2009,
    "pageCount": 222,
    "category": "Computers",
    "averageRating": 4.5,
    "imageLink": "http://books.google.com/books/content?id=-XGAPeVhRs4C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 9.95,
    "popular": false,
    "cart": false,
    "id": 48
  },
  {
    "title": "Understanding Computers: Today and Tomorrow, Comprehensive",
    "publishedDate": 2014,
    "pageCount": 752,
    "category": "Computers",
    "averageRating": 3.5,
    "imageLink": "http://books.google.com/books/content?id=TVw8AwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 91.49,
    "popular": false,
    "cart": false,
    "id": 49
  },
  {
    "title": "Computers and Art",
    "publishedDate": 2002,
    "pageCount": 159,
    "category": "Computers",
    "averageRating": 3,
    "imageLink": "http://books.google.com/books/content?id=tuYcXt71fTQC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 20,
    "popular": false,
    "cart": false,
    "id": 50
  },
  {
    "title": "Reaction-Diffusion Computers",
    "publishedDate": 2005,
    "pageCount": 348,
    "category": "Computers",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=9naAL-AkHXcC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 225,
    "popular": true,
    "cart": false,
    "id": 51
  },
  {
    "title": "Computers and Society",
    "publishedDate": 1993,
    "pageCount": 163,
    "category": "Computers",
    "averageRating": 5,
    "imageLink": "http://books.google.com/books/content?id=BckZwPywMP8C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    "price": 20,
    "popular": true,
    "cart": false,
    "id": 52
  }
]

export default books;